### ISSUE TITLE
Add concept op "basic service" to Manage

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-manage#124]
Introduce the concept of a "basic service" in Manage.  Such a Service should be automatically connected to _all_ IdPs (except when an IdP is explicitly opted-out, for example, because it is poart of an idP migration).

This allow us to define a set of basic services (like Dashboard, Community stuff, Event system, etc) to which _all_ SURFconext IdPs should be connected.

@thijskh

**Comment by thijskh** [comment]
The general concept would be useful. However at least for us there's more nuance needed. A service might in principle be connected with "all" production IdPs, but in practice it's not "all" but "nearly all", since there's always some special IdP here and there, how do we know which IdPs would be in the "all" group?

**Comment by baszoetekouw** [comment]
You're right, conceptually this is useful, but the details are still a bit hazy.  Let's close this for now and revisit it when the usecase is more pressing.
