### ISSUE TITLE
Update from 4.0.4 > 4.0.11 breaks PDP

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-manage#27]
After updating from 4.0.4 > 4.0.11 PDP breaks with the following exception:

```
Nov 18 21:34:18 webapp-4 #011java.util.NoSuchElementException: null
Nov 18 21:34:18 webapp-4 #011at java.util.HashMap$HashIterator.nextNode(HashMap.java:1447)
Nov 18 21:34:18 webapp-4 #011at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
Nov 18 21:34:18 webapp-4 #011at pdp.access.FederatedUserBuilder.getSpEntities(FederatedUserBuilder.java:92)
Nov 18 21:34:18 webapp-4 #011at pdp.access.FederatedUserBuilder.shibUser(FederatedUserBuilder.java:83)
Nov 18 21:34:18 webapp-4 #011at pdp.shibboleth.ShibbolethPreAuthenticatedProcessingFilter.getPreAuthenticatedPrincipal(ShibbolethPreAuthenticatedProcessingFilter.java:33)
```

**Comment by oharsta** [comment]
I'm not sure this is necessarily caused by Manage 4.0.11. If I run locally the PDP against the Manage version 4.0.12-SNAPSHOT then everything works. Also the PDP on our private test environment works fine. Looking at the stack-trace it appears to go wrong with the SAML Authenticating-Authority . PDP expects a Shibboleth headers named `Shib-Authenticating-Authority` which contains the IdP entity ID where the used has authenticated. This entityID must be known in Manage as it is used to lookup all the IdP's that have the same institution_id in Manage. Can you verify that the `saml:AuthenticatingAuthority` in the SAML Authn response exists in your Manage database?

**Comment by tvdijen** [comment]
That's a different issue that I reported here; https://github.com/OpenConext/OpenConext-pdp/issues/22 and leads to an `Access Denied` message..

Your comment did trigger me, because I had been experimenting with an `institution_id` of `123` on one IDP to see what it does... Removing the institution_id fixed the issue..

**Comment by oharsta** [comment]
Sadly it does. It is a bug / feature in Manage due to the backward compatibility we needed when we decided to allow for non-string values in the metadata. Long story, short version: this can be solved in Manage by looking at the actual datatype in the JSON schema, but I don't think it will be solved quickly. I can do a very quick fix in PDP, but the workaround for now is not to use numeric "liking" values in the institution_id.

**Comment by tvdijen** [comment]
I'll leave it up to you.. Institution ID's is not a feature I'm gonna use..
https://github.com/OpenConext/OpenConext-pdp/issues/22 is something that bothers me more..

**Comment by thijskh** [comment]
I'll accept it for now then, it seems not many people would run into this so we can spend our time better currently.
